apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        app: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
          app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
            - name: mysql
              image: mysql
              ports:
              - containerPort: 3306
              imagePullPolicy: Never
              volumeMounts:
                - mountPath: "/var/lib/mysql"
                  name: task-pv-storage
            volumes:
                - name: task-pv-storage
                  persistentVolumeClaim:
                    claimName: task-pvc-volume


---
apiVersion: v1
kind: Service
metadata:
        name: mysql-srv
        annotations:
            metallb.universe.tf/allow-shared-ip: shared
spec:
    selector:
        app: mysql
    clusterIP: 10.99.109.182
    ports:
            - protocol: TCP
              port: 3306
              targetPort: 3306

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#     name: task-pv-volume 
#     labels:
#         type: local
# spec:
#     storageClassName: manual 
#     capacity:
#         storage: 1Gi
#     accessModes:
#     - ReadWriteOnce 
#     persistentVolumeReclaimPolicy: Retain
#     hostPath:
#         path: "/mnt/data" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: task-pvc-volume
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi