apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: tcp
      port: 30000
      targetPort: 30000
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
      app: ftps
spec:
    selector:
      matchLabels:
        app: ftps
    replicas: 1
    template:
      metadata:
        labels:
          app: ftps
      spec:
        containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          ports:
          - containerPort: 21
          - containerPort: 30000